name: "CFN-Lint"

# Run workflow each time code is pushed to your repository and on a schedule.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run pip Install
        run: |
          pip install --upgrade pip
          pip install cfn-lint[sarif]
      # Runs the ESlint code analysis
      - name: Run cfn-lint
        # eslint exits 1 if it finds anything to report
        run: |
         ls -la
         shopt -s globstar
         cfn-lint --version
         cfn-lint ./**/*.yaml -f sarif --output results.sarif
         ls -la
      # Uploads results.sarif to GitHub repository using the upload-sarif action
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
