name: "CFN-Lint"

# Run workflow each time code is pushed to your repository and on a schedule.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run pip Install
        run: |
          pip install --upgrade pip
          pip install cfn-lint[sarif]
      - name: establish paths
        run: |
         ls -la
         pwd
         ls -la ./Projects
      # Runs the cfn-lint code analysis
      - name: Run cfn-lint
        run: |
         shopt -s globstar
         cfn-lint --version
         cfn-lint ./Projects/*.yaml -f sarif --output results.sarif
      # Uploads results.sarif to GitHub repository using the upload-sarif action
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
